### ISSUE TITLE
Group totals in the same row with group heading

### ISSUE THREAD

**Issue by smartcorestudio** [OlegKi/jqGrid#2]
Is it possible in jqGrid without writing custom code?
I want something like this (look at the green arrows). It's not jqGrid:
![2015-01-26 19_18_29-monitoring gripp _ orvi](https://cloud.githubusercontent.com/assets/2891792/5903140/065d695c-a591-11e4-9d57-438a0eed3907.png)
In jqGrid I have 2 rows for every collapsed group: one with group heading and another with values (look at the red arrows)
![2015-01-26 19_21_18- _ _ _](https://cloud.githubusercontent.com/assets/2891792/5903198/523fd710-a591-11e4-9a64-e766479b38e1.png)
But I don't want to have an extra row per group. Is it possible to make it look like the 1st screenshot using standard options of jqGrid?

**Comment by OlegKi** [comment]
The pictures which you included looks like TreeGrid. If you would calculate all totals ("всего анкет" и "средний бал") on the server side you can create data for TreeGrid. Look at [very old demo](http://www.ok-soft-gmbh.com/jqGrid/AdjacencyTreeWithHTML.htm) created for [the answer](http://stackoverflow.com/a/6509041/315935). It displays practically the same results.

So I think that the usage of TreeGrid instead of Grouping will solve your problem.

**Comment by OlegKi** [comment]
By the way one can use `groupSummaryPos: ["header"]` property of `groupingView`. It places summary grouping information in the same line with the grouping header. I think that the usage of TreeGrid for the first picture which you posted. It makes correct offsets for data rows ("1 a", "1 b") of expanded tree nodes.
