### ISSUE TITLE
how to add multipleSearch and multipleGroup to both pagers

### ISSUE THREAD

**Issue by b2dac** [OlegKi/jqGrid#4]
@OlegKi, I have two pagers. One on the top and one on the bottom of the table. How can I add multipleSearch and multipleGroup to both pagers?

Currently, I had to inspect on the generated html to find their id's (show in the below code). There must be a better way. Thanks for your help.

```javascript
		$("#grid").jqGrid(
			'navGrid',
			'#grid_toppager',
			{add: true, edit: true, del: true},
			{},
			{},
			{},
			{multipleSearch:true, multipleGroup:true}
		);
		
		$("#grid").jqGrid(
			'navGrid',
			'#jqg1',
			{add: true, edit: true, del: true},
			{},
			{},
			{},
			{multipleSearch:true, multipleGroup:true}
		);
```

**Comment by OlegKi** [comment]
If you use jqGrid 4.6/4.7 you can do the following:
````JavaScript
$.extend(true, $.jgrid.search, {multipleSearch:true, multipleGroup:true});
$("#grid").jqGrid('navGrid','#grid_toppager');
$("#grid").jqGrid('navGrid',''#jqg1');
````
Using `$.extend(true, $.jgrid.search, {...});` you changes defaults options of searching for the current HTML page. Because the options `{add: true, edit: true, del: true}` are default you can skip there.
Alternative you can use `cloneToTop:true` option of `navGrid` and to use the selector of the bottom pager as an additional parameter:
````JavaScript
$.extend(true, $.jgrid.search, {multipleSearch:true, multipleGroup:true});
$("#grid").jqGrid('navGrid',''#jqg1', {cloneToTop:true});
````
If you use the code from my fork of jqGrid the you can use simplified form of `navGrid` call:
````JavaScript
$.extend(true, $.jgrid.search, {multipleSearch:true, multipleGroup:true});
$("#grid").jqGrid('navGrid');
````
jqGrid will crates buttons on all pagers per default.
By the way my fork of jqGrid allows you to specify `pager: true` as jqGrid option. In the case you don't need to create empty pager `<div>`.
One more feature: you can set options of methods like `navGrid`, Searching dialog, form Add/Edit/Delete editing, inline editing as object options of jqGrid. So you don't need to overwrite defaults for all grids. You can for example use
````JavaScript
$("#grid").jqGrid({
    // some options
    pager: true,
    toppager: true,
    searching: { multipleSearch:true, multipleGroup:true }
}).jqGrid('navGrid');
````
In the same way you can specify any options of callbacks used by Add/Edit operation inside of `formEditing`. You can examine the source code of [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/autoresizeOnDoubleClickOnColumnResizer.htm) to see the corresponding code example.

**Comment by b2dac** [comment]
Thanks for all this great information.

I think the last section of code that you posted works best for me. But I cannot find anywhere in the documentation where it shows that "searching" is a property of jqGrid. I am looking here: http://www.trirand.com/jqgridwiki/doku.php?id=wiki:options

**Comment by OlegKi** [comment]
The options `searching`, `navOptions`, `formEditing`, `formViewing`, `formDeleting` and `inlineEditing` are **new**. I introduced it in my fork of jqGrid only you you will don't find it in the original documentation of jqGrid. I'm still in developing, but I will create the new version of the documentation in the future. Now you can find only some information of the page https://github.com/OlegKi/jqGrid (in README which will be displayed on the page).

I know many problems in existing jqGrid and try to implement the corresponding solutions. If you tried to configure inline editing or form editing options you could have to spend many time in placing the option in the correct place. If you need just to use <kbd>Enter</kbd> and <kbd>Esc</kbd> keys for inline editing you will have to set `keys: true` option of [editRow](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:inline_editing#editrow) in general, but if you don't call `editRow` and you use [formatter: "actions"](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:predefined_formatter#predefined_format_types) or [inlineNav](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:inline_editing#inlinenav) then you will have to place `keys: true` inside of relatively complex wrapper options. The usage of `inlineEditing: {keys: true}` is much more intuitive and it specifies the inline editing options inside of the grid independent from the way of usage inline editing.

I will create soon the documentation about the new options.

**Comment by b2dac** [comment]
Okay, that explains it. Thanks again.

Yes please, if you could update your fork's documentation that would be great. :smiley:
