### ISSUE TITLE
can't make reliable row selections when subGrid is enabled

### ISSUE THREAD

**Issue by bchr02** [OlegKi/jqGrid#7]
One can't make reliable row selections when subGrid is enabled. Sometimes the wrong row(s) become selected. Removing or setting subGroup to false causes all to work fine. 

Please see my demo in the below link. Thanks.

Please have a look at: http://www.tesllc.aero/temp/jqgrid/index.html

**Comment by OlegKi** [comment]
First of all you don't use subgrids in the grid. Probably you have problems with selections of row of grouped data? I'm not wonder about it because you have error in the grid

The demo have clear bug: The column `CQD_AUTO_KEY`contains `key: true` property, but the data in the column are **not unique**. You can just remove `key: true` property to fix the problem. In the case jqGrid will generate 1,2,3... as row ids. If you need to have more informative rowids and you can't change the input data then you should fill *additional* `id` property based on other properties. For example as `item.CQD_AUTO_KEY` + "_" +  `item.SALESPERSON_NAME`. Such input data can be easier edited in the future.

**Comment by b2dac** [comment]
Thanks. Good catch. I changed all the CQD_AUTO_KEY so they are unique. I also made them all into strings. But even after doing this, I still have the error. Since I currently have no need for using key: true I will just remove this. However, this appears to still be a bug. I left the site up if you want to have a look.

**Comment by OlegKi** [comment]
Thank you. I could reproduce the problem, found a bug and have fixed the code. Please refresh `jquery.jqGrid.src.js` which you use.
